/-
Copyright 2026 The Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Hoang Le Truong
-/
import Curve25519Dalek.Funs
import Curve25519Dalek.Math.Basic
import Curve25519Dalek.Math.Montgomery.Representation
import Curve25519Dalek.Specs.Montgomery.MontgomeryPoint.Mul

/-!
# Spec theorem for `curve25519_dalek::montgomery::MontgomeryPoint::mul_assign`

Computes the scalar multiplication `[s]P` on the Montgomery curve in-place, where `s` is a
`Scalar` and `P` is a `MontgomeryPoint` (u-coordinate only). The implementation delegates to
the `MontgomeryPoint * Scalar` routine, which uses the Montgomery ladder on the u-coordinate.

This file covers two Lean extraction variants: the primary implementation
(`CoreOpsArithMulAssignShared0Scalar`) from `montgomery.rs` and a by-value
`MontgomeryPoint *= Scalar` wrapper (`CoreOpsArithMulAssignScalar`) generated via the
`define_mul_assign_variants!` macro in `macros.rs`, which delegates directly to the primary
implementation.

Source: "curve25519-dalek/src/montgomery.rs"
-/

open Aeneas Aeneas.Std Result Aeneas.Std.WP
open Montgomery
namespace curve25519_dalek.montgomery.MontgomeryPoint.Insts.CoreOpsArithMulAssignShared0Scalar

/-- **Spec theorem for `curve25519_dalek::montgomery::MontgomeryPoint::mul_assign`**
• The function always succeeds (no panic)
• The result satisfies `MontgomeryPoint.mkPoint result = m • MontgomeryPoint.mkPoint self`,
  where `m = (U8x32_as_Nat scalar.bytes) % 2^255`
-/
@[step]
theorem mul_assign_spec (self : MontgomeryPoint) (scalar : scalar.Scalar)
    (hself_bound : U8x32_as_Nat self < 2 ^ 255) :
    mul_assign self scalar ⦃ (result : MontgomeryPoint) =>
      let m := (U8x32_as_Nat scalar.bytes) % 2^255
      MontgomeryPoint.mkPoint result = m • (MontgomeryPoint.mkPoint self) ⦄ := by
  unfold mul_assign
  step*

end curve25519_dalek.montgomery.MontgomeryPoint.Insts.CoreOpsArithMulAssignShared0Scalar

/-! ## Wrapper: `MontgomeryPoint *= Scalar` (by-value rhs)

The following variant wraps the core `MontgomeryPoint *= &Scalar` implementation by
delegating directly to `CoreOpsArithMulAssignShared0Scalar.mul_assign`. In the Lean extraction,
`rhs` is passed by value (corresponding to the Rust `Scalar` value). Generated by the
`define_mul_assign_variants!` macro (macros.rs, lines 118:12-120:13).
-/

namespace curve25519_dalek.montgomery.MontgomeryPoint.Insts.CoreOpsArithMulAssignScalar

/-- **Spec theorem for `curve25519_dalek::montgomery::MontgomeryPoint::mul_assign`**
• The function always succeeds (no panic)
• The result satisfies `MontgomeryPoint.mkPoint result = m • MontgomeryPoint.mkPoint self`,
  where `m = (U8x32_as_Nat rhs.bytes) % 2^255`
-/
@[step]
theorem mul_assign_spec (self : MontgomeryPoint) (rhs : scalar.Scalar)
    (hself_bound : U8x32_as_Nat self < 2 ^ 255) :
    mul_assign self rhs ⦃ (result : MontgomeryPoint) =>
      let m := (U8x32_as_Nat rhs.bytes) % 2^255
      MontgomeryPoint.mkPoint result = m • (MontgomeryPoint.mkPoint self) ⦄ := by
  unfold mul_assign
  step*

end curve25519_dalek.montgomery.MontgomeryPoint.Insts.CoreOpsArithMulAssignScalar
