/-
Copyright 2026 The Beneficial AI Foundation. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Markus Dablander
-/
import Curve25519Dalek.Funs
import Curve25519Dalek.Math.Edwards.EightTorsion
import Curve25519Dalek.Math.Edwards.Representation
import Curve25519Dalek.Specs.Backend.Serial.U64.Field.FieldElement51.FromLimbs

/-! # Spec theorem for `curve25519_dalek::backend::serial::u64::constants::EIGHT_TORSION`

This constant represents the eight-torsion subgroup E[8] of the Edwards curve, which
consists of eight points P_0, ..., P_7 such that [8]P_i = 0. For Curve25519 this subgroup
is cyclic and is generated by a point P of order eight.

The array is organised so that the i-th element is [i]P, where P is a generator of order
eight. This implies that:

• E[4] (the four-torsion subgroup) corresponds to indices 0, 2, 4, 6
• E[2] (the two-torsion subgroup) corresponds to indices 0, 4

Source: "curve25519-dalek/src/backend/serial/u64/constants.rs"
-/

open Aeneas Aeneas.Std Result Aeneas.Std.WP
open Edwards
namespace curve25519_dalek.backend.serial.u64.constants

/-- **Spec theorem for `curve25519_dalek::backend::serial::u64::constants::EIGHT_TORSION`**
• The function always succeeds (no panic)
• `P := EIGHT_TORSION[1]` is a valid `EdwardsPoint`
• `P` has order exactly eight (`4 • P ≠ 0` and `8 • P = 0`)
• Each `EIGHT_TORSION[i]` (`i ∈ {0,...,7}`) is a valid `EdwardsPoint`
• Each `EIGHT_TORSION[i]` represents `[i] • P` on the Edwards curve
-/
@[step]
theorem EIGHT_TORSION_spec :
    EIGHT_TORSION ⦃ (result : Array edwards.EdwardsPoint 8#usize) =>
      let P := result.val[1]
      P.IsValid ∧ 4 • P.toPoint ≠ 0 ∧ 8 • P.toPoint = 0 ∧
      (∀ (i : Fin 8), result.val[i].IsValid) ∧
      (∀ (i : Fin 8), result.val[i].toPoint = (i : ℕ) • P.toPoint) ⦄ := by
  unfold EIGHT_TORSION EIGHT_TORSION_INNER_DOC_HIDDEN
  step*
  refine ⟨?_, ?_, ?_, ?_, ?_⟩
  · simp only [Array.make, List.getElem_cons_succ, List.getElem_cons_zero, *]; decide
  · -- 4 • P.toPoint ≠ 0
    simp only [Array.make, List.getElem_cons_succ, List.getElem_cons_zero, *]
    change 4 • _root_.Edwards.eightTorsionGen ≠ 0
    exact _root_.Edwards.four_nsmul_gen_ne_zero
  · -- 8 • P.toPoint = 0
    simp only [Array.make, List.getElem_cons_succ, List.getElem_cons_zero, *]
    change 8 • _root_.Edwards.eightTorsionGen = 0
    exact _root_.Edwards.eight_nsmul_gen_eq_zero
  · -- ∀ i, result.val[i].IsValid
    intro i; fin_cases i
    all_goals
    · simp only [Array.make, Fin.getElem_fin, List.getElem_cons_succ, List.getElem_cons_zero, *]
      decide
  · -- ∀ i, result.val[i].toPoint = (i : ℕ) • P.toPoint
    intro i;
    have h := _root_.Edwards.nsmul_eightTorsionGen_eq ⟨i, by omega⟩
    fin_cases i
    all_goals
    · simp only [Array.make, Fin.getElem_fin, List.getElem_cons_succ, List.getElem_cons_zero, *]
      exact h.symm

end curve25519_dalek.backend.serial.u64.constants
